"""
intel.waf_matrix — WAF fingerprint -> bypass playbook.
Fingerprints by response headers, cookies, error body shapes, status codes.
Returns a ranked list of bypass strategies.
"""
import re
import json

# signature: (name, header_keys, cookie_keys, body_needles, server_needles)
SIGNATURES = [
    ("cloudflare",     ["cf-ray", "cf-cache-status", "cf-request-id"],
                       ["__cfduid", "__cf_bm", "cf_clearance"], [], []),
    ("akamai",         ["x-akamai-transformed", "akamai-grn", "x-akamai-request-id"],
                       ["ak_bmsc", "bm_sv", "bm_sz", "akavpau"], [], []),
    ("aws_waf",        ["x-amzn-requestid", "x-amz-cf-id", "x-amzn-trace-id"],
                       ["aws-waf-token"], [], []),
    ("cloudfront",     ["x-amz-cf-pop", "x-amz-cf-id", "x-cache"],
                       [], ["Request blocked"], []),
    ("sucuri",         ["x-sucuri-id", "x-sucuri-cache"],
                       ["sucuri_cloudproxy_uuid"], ["Sucuri WebSite Firewall"], ["Sucuri/Cloudproxy"]),
    ("imperva_incapsula", ["x-iinfo", "x-cdn"],
                       ["incap_ses", "visid_incap"], ["Incapsula incident ID"], ["Incapsula"]),
    ("f5_bigip_asm",   ["x-wa-info"],
                       ["TS01", "BIGipServer", "TS"],
                       ["The requested URL was rejected"], []),
    ("fortiweb",       ["x-fw-hash", "x-fw-debug"],
                       ["FORTIWAFSID"], ["FortiWeb"], []),
    ("barracuda",      [], ["barra_counter_session"],
                       ["Barracuda"], []),
    ("mod_security",   [],
                       [], ["ModSecurity", "Not Acceptable", "mod_security", "Atomicorp"],
                       ["Apache"]),
    ("wordfence",      [],
                       ["wfvt_", "wordfence_verifiedHuman"],
                       ["Generated by Wordfence", "wordfence"], []),
    ("nginx_naxsi",    [], [], ["naxsi"], ["nginx"]),
    ("reblaze",        ["rbzid", "x-rbz-id"], ["rbzsessionid"], [], []),
    ("radware",        ["x-sl-compstate"], ["rbzid"], [], []),
    ("stackpath",      ["x-sp-url", "x-sp-waf"], [], [], []),
    ("fastly",         ["x-fastly-request-id", "x-served-by", "fastly-debug-digest"],
                       [], [], ["Fastly"]),
    ("varnish",        ["x-varnish", "via"], [], [], ["Varnish"]),
    ("envoy",          ["x-envoy-upstream-service-time", "x-envoy-decorator-operation"],
                       [], [], []),
    ("traefik",        ["x-forwarded-server"], [], [], []),
    ("gcp_cloud_armor",["x-cloud-trace-context"],
                       [], [], []),
]

# bypass strategies, ordered by typical success rate
STRATEGIES = {
    "default": [
        "case_flip: /Admin, /aDmin, /ADMIN vs /admin",
        "double_encode: %252e%252e%252f, %2527 for '",
        "unicode_norm: ᵃ dmin, ../%c0%ae variants",
        "path_segments: /./admin //admin /admin/. /admin;/",
        "trailing_dot_slash: /admin., /admin..;/",
        "comment_inject: /*x*/union/*y*/select",
        "whitespace_swap: space -> tab(%09), newline(%0a), vtab(%0b)",
        "content_type_flip: application/x-www-form-urlencoded <-> application/json",
        "method_swap: POST->PUT->PATCH->OPTIONS",
        "chunked_encoding: Transfer-Encoding: chunked with split payload",
        "hpp: ?id=1&id=2  (HTTP parameter pollution)",
        "hex_escape: %41 = A, mixed hex/case",
    ],
    "cloudflare": [
        "wait_and_retry: CF challenge expires after ~60s",
        "ua_rotate: real Chrome UA + Accept-Language + Accept-Encoding",
        "header_order: match real Chrome header order via curl --http2",
        "slow_ladder: 1 rps for 30s, then ramp",
        "ip_rotate: residential proxy needed if challenge persists",
        "json_content_type: CF often misses JSON body attacks",
        "unicode_escape: \\u0027 instead of '",
        "multipart_boundary: wrap payload in multipart",
    ],
    "akamai": [
        "ua_allowlist: match a known-good UA (Googlebot may pass)",
        "akamai_headers: ensure all client hints present (sec-ch-ua*)",
        "cookie_replay: if _abck cookie obtained, replay it",
        "path_case: Akamai is case-sensitive, try /Admin",
        "hop_by_hop: add X-Forwarded-Host, X-Original-URL",
    ],
    "aws_waf": [
        "json_body: AWS WAF inspects form-data more than JSON",
        "unicode_escape: \\u003c for <",
        "large_body: pad with 8KB of junk to push payload past inspection window",
        "regex_dos: force timeout with pathological regex-triggering payloads",
        "path_normalize: AWS normalizes // but not /./  try /.%2fadmin",
    ],
    "sucuri": [
        "x-forwarded-for: spoof client IP to 127.0.0.1",
        "content_type: Sucuri fails to inspect multipart/form-data with specific boundaries",
        "cookie_bypass: sucuri_cloudproxy_uuid_<random> may skip checks",
        "low_and_slow: rate-limit to 1 req/2s",
    ],
    "imperva_incapsula": [
        "x-forwarded-for: 127.0.0.1 or X-Real-IP",
        "double_encoding",
        "utf7_bypass: +ADw-script+AD4-",
        "content_type_text: Content-Type: text/plain may bypass XSS checks",
    ],
    "f5_bigip_asm": [
        "x-forwarded-for: 127.0.0.1",
        "malformed_json: trailing comma, extra whitespace",
        "content_length_mismatch: Content-Length larger than actual body",
        "gzip_body: content-encoding: gzip hides payload",
    ],
    "mod_security": [
        "case_flip",
        "double_encode",
        "sql_comment: union/**/select",
        "concat: CONCAT(0x41) instead of 'A'",
        "char_func: CHAR(65) for A",
        "utf_encoding: use %u0027 (IIS style) if server tolerates",
    ],
    "wordfence": [
        "x-forwarded-for: 127.0.0.1",
        "user_agent: WordPress/6.4 + WordPress/5.0",
        "referer: https://<target>/wp-admin/",
        "wp_json_api: /wp-json/wp/v2/... may be exempt",
    ],
}

# detection helpers

def _has(d, keys):
    if not d:
        return False
    dl = {k.lower(): str(v).lower() for k, v in d.items()}
    for k in keys:
        if k.lower() in dl:
            return True
    return False

def _cookie_has(cookies, keys):
    if not cookies:
        return False
    joined = " ".join(f"{k}={v}" for k, v in cookies.items()).lower()
    return any(k.lower() in joined for k in keys)

def _body_has(body, needles):
    if not body or not needles:
        return False
    b = body.lower()
    return any(n.lower() in b for n in needles)

def _server_has(server, needles):
    if not server or not needles:
        return False
    s = server.lower()
    return any(n.lower() in s for n in needles)


def detect(headers, cookies=None, body="", status=None, server=None):
    """Return a list of (name, score) candidates, highest first."""
    if not server and headers:
        server = headers.get("server") or headers.get("Server")
    hits = []
    for name, hk, ck, bn, sn in SIGNATURES:
        score = 0
        if hk and _has(headers, hk):
            score += 3 * len([k for k in hk if k.lower() in {x.lower() for x in headers}])
        if ck and _cookie_has(cookies, ck):
            score += 3
        if bn and _body_has(body, bn):
            score += 4
        if sn and _server_has(server, sn):
            score += 2
        if score > 0:
            hits.append((name, score))
    hits.sort(key=lambda x: -x[1])
    return hits


def bypass_playbook(waf_name):
    """Return ranked bypass strategies for a WAF name."""
    name = (waf_name or "").lower().replace("-", "_")
    specific = STRATEGIES.get(name, [])
    default = STRATEGIES["default"]
    return specific + [d for d in default if d not in specific]


def full_report(headers, cookies=None, body="", status=None, server=None):
    hits = detect(headers, cookies, body, status, server)
    report = {
        "detected": [h[0] for h in hits],
        "confidence": hits[0][1] if hits else 0,
        "playbook": bypass_playbook(hits[0][0]) if hits else bypass_playbook(None),
    }
    return report


if __name__ == "__main__":
    # demo fingerprint
    sample = {
        "cf-ray": "abc123",
        "server": "cloudflare",
        "cf-cache-status": "HIT",
    }
    print(json.dumps(full_report(sample, {"__cfduid": "x"}), indent=2))
